package org.recommend.www.mapper.db.recommend;

import org.apache.ibatis.annotations.Param;
import org.recommend.www.dto.ItemSimiScore;

import java.util.List;

public interface ItemSimiScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int insert(ItemSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int insertSelective(ItemSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    ItemSimiScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int updateByPrimaryKeySelective(ItemSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int updateByPrimaryKey(ItemSimiScore record);


    List<ItemSimiScore> selectBySourceId(@Param("id") String sourceId,@Param("pageSize") Integer pageSize);
}