package org.recommend.www.mapper.db.recommend;

import org.apache.ibatis.annotations.Param;
import org.recommend.www.dto.TitleSimiScore;

import java.util.List;

public interface TitleSimiScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int insert(TitleSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int insertSelective(TitleSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    TitleSimiScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int updateByPrimaryKeySelective(TitleSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title_simi_score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    int updateByPrimaryKey(TitleSimiScore record);



    List<TitleSimiScore> selectBySourceId(@Param("id") Integer titleIdA,@Param("pageSize") Integer pageSize);
}