package org.recommend.www.dto;

import java.util.Date;

public class ItemSimiScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.item_id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.target_item_id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private String targetItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.add_date
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.id
     *
     * @return the value of item_simi_score.id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.id
     *
     * @param id the value for item_simi_score.id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.item_id
     *
     * @return the value of item_simi_score.item_id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.item_id
     *
     * @param itemId the value for item_simi_score.item_id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.target_item_id
     *
     * @return the value of item_simi_score.target_item_id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public String getTargetItemId() {
        return targetItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.target_item_id
     *
     * @param targetItemId the value for item_simi_score.target_item_id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setTargetItemId(String targetItemId) {
        this.targetItemId = targetItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.score
     *
     * @return the value of item_simi_score.score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.score
     *
     * @param score the value for item_simi_score.score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.add_date
     *
     * @return the value of item_simi_score.add_date
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.add_date
     *
     * @param addDate the value for item_simi_score.add_date
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}