package org.recommend.www.dto;

import java.util.Date;

public class TitleSimiScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_simi_score.id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_simi_score.title_id_a
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private String titleIdA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_simi_score.title_id_b
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private String titleIdB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_simi_score.score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title_simi_score.add_time
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_simi_score.id
     *
     * @return the value of title_simi_score.id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_simi_score.id
     *
     * @param id the value for title_simi_score.id
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_simi_score.title_id_a
     *
     * @return the value of title_simi_score.title_id_a
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public String getTitleIdA() {
        return titleIdA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_simi_score.title_id_a
     *
     * @param titleIdA the value for title_simi_score.title_id_a
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setTitleIdA(String titleIdA) {
        this.titleIdA = titleIdA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_simi_score.title_id_b
     *
     * @return the value of title_simi_score.title_id_b
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public String getTitleIdB() {
        return titleIdB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_simi_score.title_id_b
     *
     * @param titleIdB the value for title_simi_score.title_id_b
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setTitleIdB(String titleIdB) {
        this.titleIdB = titleIdB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_simi_score.score
     *
     * @return the value of title_simi_score.score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_simi_score.score
     *
     * @param score the value for title_simi_score.score
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title_simi_score.add_time
     *
     * @return the value of title_simi_score.add_time
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title_simi_score.add_time
     *
     * @param addTime the value for title_simi_score.add_time
     *
     * @mbggenerated Wed Aug 10 22:12:18 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}